### ISSUE TITLE
Setup golangci-lint with proper config.

### ISSUE THREAD

**Issue by marcbinz** [go-surreal/som#7]
- [x] Add golangci-lint config file. (#51)
- [x] Add linting to PR workflow. (#51)
- [x] Fix initial issues. (#52)
- [ ] Also lint the example/gen folder.
- [ ] Add in-depth rules (with fixes) to config.
